frr version 10
frr defaults traditional
hostname r4
log stdout
!
interface eth3
 ip address 10.20.20.1/24
!
router ospf
 network 10.0.24.0/30 area 0
 network 10.0.34.0/30 area 0
 network 10.20.20.0/24 area 0
!
